name: Build and push container image

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  

env:
  IMAGE_REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAGS: ${{ github.sha }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}


jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Buildah Build
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }}
          
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Parse semver tag
        id: semver
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo semver=$( echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//' ) >> "$GITHUB_OUTPUT"
          echo "SEMVER=$( echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//' )" >> "$GITHUB_ENV"
      

      - name: Add semver tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          podman tag ${{ steps.build_image.outputs.image }}:${{ github.sha }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.semver }}
          podman tag ${{ steps.build_image.outputs.image }}:${{ github.sha }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          echo "IMAGE_TAGS=${{ steps.semver.outputs.semver }}" >> "$GITHUB_ENV"
      # If this is a semver tag, also push as latest and major.minor.patch
      - name: Push Semver Tags
        if: startsWith(github.ref, 'refs/tags/v')
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: latest ${{ steps.semver.outputs.semver }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
