name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Packages 
      run: pip install pyyaml coverage
      
    - name: Run tests
      run: python -m coverage run -m unittest discover -s tests
       
    - name: Create coverage badges
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        style: classic
        source: coverage.json
        output: coverage/badges.svg
        jsonPath: totals.percent_covered

    - name: Deploy coverage badge
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage
