name: Unit tests to ensure only valid code is pushed

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Packages 
      run : pip install pyyaml
      
    - name : Run tests
      run : python -m unittest discover -s tests
