name: Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Packages 
      run: pip install pyyaml coverage
      
    - name: Run tests
      run: python -m coverage run -m unittest discover -s tests

    - name: Generate coverage json report
      if: github.ref == 'refs/heads/main'
      run: python -m coverage json
      
    - name: Generate output dir
      if: github.ref == 'refs/heads/main'
      run: mkdir ./coverage
      
    - name: Generate coverage html report
      if: github.ref == 'refs/heads/main'
      run: python -m coverage html -d ./coverage
        
    - name: Create coverage badges
      uses: jaywcjlove/coverage-badges-cli@main
      if: github.ref == 'refs/heads/main'
      with:
        style: classic
        source: coverage.json
        output: coverage/badges.svg
        jsonPath: totals.percent_covered_display
    
    - name: Build root web directory structure
      if: github.ref == 'refs/heads/main'
      run: mkdir public && mv coverage public/
      
    - name: Deploy coverage badge and site
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        #keep_files: true
